<a href="https://colab.research.google.com/github/creamcheesesteak/Project_EasterEgg/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
len(code2idx)

14

In [5]:
code2idx['g8']

11

In [6]:
range(len(note_seq)-4) # [4, 8, 12 ...]

range(0, 50)

In [7]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # print(code2idx[item])
    items.append(code2idx[item])
    # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [8]:
import numpy as np

In [9]:
datasets = np.array(dataset)

In [10]:
x_train = datasets[:,0:3]
x_train.shape, # x_train

((50, 3),)

In [11]:
y_train = datasets[:,3]
y_train.shape, # y_train

((50,),)

In [12]:
x_train = x_train / 13  # len(code2dix)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [13]:
import tensorflow as tf
model = tf.keras.models.Sequential()

In [14]:
x_train.shape # --> tensorflow type(tensor)  (50,3,1)
x_train[2]

array([0.15384615, 0.76923077, 0.61538462])

In [15]:
X_train = np.reshape(x_train, (50, 3, 1))
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [16]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [17]:
model.add(tf.keras.Input(shape=(3,1)))
model.add(tf.keras.layers.LSTM(128)) # input layer, column의 값을 input으로
# LSTM(batch_size, timesteps, input_dim) -> (row, cols, )
# model.add() # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [24]:
hist = model.fit(X_train, y_train, epochs=2000, batch_size=10)

Epoch 1/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2031 - accuracy: 0.5600
Epoch 2/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2054 - accuracy: 0.5600
Epoch 3/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2044 - accuracy: 0.5600
Epoch 4/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2205 - accuracy: 0.5600
Epoch 5/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2162 - accuracy: 0.5800
Epoch 6/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.1991 - accuracy: 0.5200
Epoch 7/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2072 - accuracy: 0.5200
Epoch 8/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2079 - accuracy: 0.4600
Epoch 9/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2038 - accuracy: 0.5400
Epoch 10/2000
5/5 [==============================] - 0s 5ms/step - loss: 1.2042 - accuracy: 0.5800
Epoch 11/2000
5/5 [

In [19]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 0s 7ms/step - loss: 1.9444 - accuracy: 0.3400


[1.9444409608840942, 0.3400000035762787]

In [21]:
X_train[4:5]

array([[[0.61538462],
        [0.07692308],
        [0.53846154]]])

In [ ]:
# [[[0.61538462], [0.07692308], [0.53846154]]]
# first = 0.61538462
# second = 0.07692308
# third = 0.53846154
# model.predict([[[first],[second],[third]]])

In [22]:
model.predict(X_train[4:5])

array([[0.01516762, 0.04162981, 0.06333496, 0.03554539, 0.04658756,
        0.01340181, 0.01293817, 0.0522815 , 0.15106153, 0.3294689 ,
        0.08566157, 0.13946766, 0.01345342]], dtype=float32)

In [25]:
pred = model.predict(X_train[0:1])

In [27]:
np.argmax(pred)

10

# note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4', 'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4', 'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4', 'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

# code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6, 'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}